//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.TitlePanelControlDesignDatat
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class TitlePanelControlDesignDatat { }
#else

	public class TitlePanelControlDesignDatat : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public TitlePanelControlDesignDatat()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/TestYourself;component/SampleData/TitlePanelControlDesignDatat/TitlePanelControlDesignDatat.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private string _TitleName = string.Empty;

		public string TitleName
		{
			get
			{
				return this._TitleName;
			}

			set
			{
				if (this._TitleName != value)
				{
					this._TitleName = value;
					this.OnPropertyChanged("TitleName");
				}
			}
		}
	}
#endif
}
